config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :enquetes, except: [:index]
  resources :replies, only: [:show, :edit, :update]
  resources :teams, only: [:index, :show]
  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @enquetes = Enquete.where(sender: current_user)
    @replies = Reply.where(user: current_user).order(created_at: :desc)
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
  # ログインユーザーがマネージャかどうかを返す
  def manager?
    Team.find_by(manager: current_user).present?
  end
end

app/views/home/_enquetes.html.erb
<h4><i class="bi bi-send"></i> 送信したアンケート</h4>

<% if @enquetes.any? %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">タイトル</th>
        <th scope="col">送信日</th>
        <th scope="col">回答状況</th>
        <th scope="col">回答期限</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @enquetes.each do |enq| %>
      <tr>
        <td><%= link_to enq.title, enq %></td>
        <td><%= enq.created_at.strftime("%Y-%m-%d %H:%M") %></td>
        <td>
          <%= "#{enq.replies.where.not(submitted_at: nil).size} / #{enq.replies.size}" %>
        </td>
        <td>
          <%= enq.deadline %>
          <span class="<%= remain_class(enq.deadline)%>">
            <%= "（#{show_remain(enq.deadline)}）"%>
          </span>
        </td>
        <td>
          <%= link_to "詳細", enq, class: "btn btn-sm btn-success" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>アンケートはまだありません。</p>
<% end%>
<%= link_to "アンケート作成", :new_enquete, class: "btn btn-primary" %>

app/views/home/_replies.html.erb
<h4><i class="bi bi-pencil"></i> あなたへのアンケート</h4>

<% if @replies.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>タイトル</th>
        <th>送信日</th>
        <th>送信者</th>
        <th>回答期限</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @replies.each do |reply| %>
      <tr>
        <td><%= link_to reply.enquete.title, edit_reply_path(reply.id) %></td>
        <td><%= reply.enquete.created_at.strftime("%Y-%m-%d %H:%M") %></td>
        <td><%= reply.enquete.sender.user_name %></td>
        <td>
          <%= reply.enquete.deadline %>
          <span class="<%= remain_class(reply.enquete.deadline)%>">
            <%= "（#{show_remain(reply.enquete.deadline)}）"%>
          </span>
        </td>
        <td>
          <% if reply.submitted_at.nil? %>
            <%= link_to "回答", edit_reply_path(reply.id), class: "btn btn-sm btn-warning" %>
          <% else %>
            <%= link_to "回答済", edit_reply_path(reply.id), class: "btn btn-sm btn-dark" %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  アンケートはありません。
<% end %>

app/views/home/index.html.erb
<div class="mt-5">
  <%= render 'home/replies' %>
</div>
<div></div>
<div class="mt-5">
  <% if manager? %>
    <%= render 'home/enquetes' %>
  <% end %>
</div>