config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :enquetes, except: [:index]
  resources :replies, only: [:show, :edit, :update]
  resources :teams, only: [:index, :show]
  root to: "home#index"
end

app/models/enquete.rb
class Enquete < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :replies, dependent: :destroy
  default_scope { order(created_at: :desc) }

  validates :title, presence: true
  validates :deadline, presence: true
  validate  :deadline_gte_today

  private
    def deadline_gte_today
      unless deadline.blank?
        if deadline < Date.today
          errors.add(:deadline, "は本日以降の日付を入力してください")
        end
      end
    end
end

app/controllers/enquetes_controller.rb
class EnquetesController < ApplicationController
  require 'csv'
  before_action :authenticate_user!
  before_action :manager_user
  before_action :sender_user, only: [:show, :edit, :update, :delete]

  def show
    @enquete = Enquete.find(params[:id])
    respond_to do |format|
      format.html
      format.csv {send_csv(@enquete)}
    end
  end

  def new
    @form = EnquetesForm.new
    @users = managed_team_users
    @form.users = @users.ids
  end

  def create
    @form = EnquetesForm.new(enquete_form_params)
    @form.sender_id = current_user.id
    if @form.save
      flash[:notice] = "アンケートを送信しました。"
      redirect_to root_url
    else
      flash.now[:error] = "入力に誤りがあります。"
      @users = managed_team_users
      render :new
    end
  end

  def edit
    @enquete = Enquete.find(params[:id])
    @users = managed_team_users
  end

  def update
    @enquete = Enquete.find(params[:id])
    if @enquete.update(enquete_update_params)
      flash[:notice] = "アンケートを更新しました。"
      redirect_to enquete_url(params[:id])
    else
      flash.now[:error] = "入力に誤りがあります。"
      @users = managed_team_users
      render :edit
    end
  end

  def destroy
    @enquete = Enquete.find(params[:id])
    @enquete.destroy
    flash[:notice] = "アンケートを削除しました。"
    redirect_to root_url
  end

  private
    def enquete_form_params
      params.require(:enquete).permit(:title, :deadline, users: [])
    end

    def enquete_update_params
      params.require(:enquete).permit(:title, :deadline)
    end

    def managed_teams
      Team.where(manager: current_user)
    end

    def managed_team_users
      User.joins(:team_users).where('team_users.team_id IN (?)', managed_teams.ids)
    end

    # マネージャのみ使用可能
    def manager_user
      unless managed_teams.present?
        flash[:alert] = "アクセスできません。"
        redirect_to root_url
      end
    end

    # 作成後のアンケートは、送信者のみ参照・編集可能
    def sender_user
      enquete = Enquete.find_by(id: params[:id])
      unless enquete && enquete.sender == current_user
        flash[:alert] = "アクセスできません。"
        redirect_to root_url
      end
    end

    # CSV出力処理
    def send_csv(enquete)
      bom = "\uFEFF"
      data = CSV.generate(bom, force_quotes: true) do |csv|
        csv << CSV_COLUMNS
        enquete.replies.each do |reply|
          csv << reply.to_csv
        end
      end
      send_data(data, filename: "enqreply_#{Time.current.strftime("%Y%m%d%H%M%S")}.csv")
    end

    # CSVヘッダカラム
    CSV_COLUMNS = %w(
      氏名 回答日時 社員番号 グレード ステータス
      PJ_テクニカル・スキル PJ_人間関係 PJ_アピール・問題点
      希望職種 1年後_グレード 1年後_人材イメージ 1年後_行動・目標
      3年後_グレード 3年後_人材イメージ 3年後_行動・目標
      5年後_グレード 5年後_人材イメージ 5年後_行動・目標
      現_CD目標① 現_進捗率① 現_進捗状況① 現_弊害・問題点①
      現_CD目標② 現_進捗率② 現_進捗状況② 現_弊害・問題点②
      次_CD目標① 次_分配率① 次_CD目標② 次_分配率②
      受講日・セミナー名 受講時間合計
      業務知識 顧客評価・CSサービス 会社貢献度 仕事の量・質 積極性 規律性 責任性
      上長マネージャに対する要望 営業部に対する要望 管理部に対する要望 会社に対する要望
    )
end

app/helpers/enquetes_helper.rb
module EnquetesHelper
  # 期限まであと何日かを返す
  def remain(date)
    (date - Date.current).to_i
  end

  # 「あと何日」の表示を行う
  def show_remain(date)
    r = remain(date)
    if r < 0
      "期限切れ"
    elsif r == 0
      "今日まで"
    else
      "あと#{r}日"
    end
  end

  # 「あと何日」を表示する際のclass
  def remain_class(date)
    r = remain(date)
    if r > 7
      "text-success"
    elsif r > 3
      "text-primary"
    elsif r > 0
      "text-danger"
    elsif r == 0
      "text-danger fw-bold"
    else
      "text-muted"
    end
  end

end

app/views/enquetes/edit.html.erb
<h1>アンケート変更</h1>

<%= form_with(model: @enquete, method: :put, local: true, data: { confirm: "アンケートを更新します。よろしいですか？" }) do |f| %>
  <div class="mb-3 row">
    <%= f.label :title, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="mb-3 row">
    <%= f.label :deadline, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.date_field :deadline, class: "form-control" %>
    </div>
  </div>
  <div class="mb-3 row">
    <%= f.label :users, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.select :users, options_for_select(@users.map{|u|[u.user_name, u.id]}, @enquete.replies.map{|r|r.user.id}), {}, {multiple: true, size: 10, class: "form-select", disabled: true} %>
    </div>
  </div>
  <div class="m-5 row">
    <%= f.submit "更新", class:"btn btn-info" %>
  </div>
<% end %>

app/views/enquetes/new.html.erb
<h1>新規アンケート</h1>
<p class="text-muted">アンケート送信ボタンを押すと、送信先に通知されます。</p>

<%= form_with(model: @form, url: enquetes_path, local: true, data: { confirm: "アンケートを送信します。よろしいですか？" }) do |f| %>
  <div class="mb-3 row">
    <%= f.label :title, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="mb-3 row">
    <%= f.label :deadline, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.date_field :deadline, value: @form.deadline, class: "form-control" %>
    </div>
  </div>
  <div class="mb-3 row">
    <%= f.label :users, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.select :users, options_for_select(@users.map{|u|[u.user_name, u.id]}, @form.users), {}, {multiple: true, size: 10, class: "form-select"} %>
    </div>
  </div>
  <div class="m-5 row">
    <%= f.submit "アンケート送信", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/enquetes/show.html.erb
<p class="h1 mb-3"><%= @enquete.title%></p>
<p><%= "送信日 : #{@enquete.created_at.strftime("%Y-%m-%d %H:%M:%S")}"%></p>
<p><%= "送信者 : #{@enquete.sender.user_name}" %></p>
<p><%= "提出期限 : #{@enquete.deadline} （#{show_remain(@enquete.deadline)}）"%></p>
<table class="table">
  <thead>
    <tr>
      <th>氏名</th>
      <th>最終更新日</th>
      <th>回答状況</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @enquete.replies.each do |reply| %>
    <tr>
      <td><%= reply.user.user_name%></td>
      <td><%= reply.updated_at.strftime("%Y-%m-%d %H:%M:%S") if reply.update_count > 0 %></td>
      <td><%= !reply.submitted_at.nil? ? "回答済" : (reply.update_count > 0 ? "回答中" : "未回答") %></td>
      <td><%= link_to "詳細", reply, class: "btn btn-sm btn-secondary" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="d-flex">
  <%= link_to "CSV出力", enquete_path(id: @enquete.id, format: :csv), class: "btn btn-success flex-grow-1 me-2" %>

  <%= link_to "回答期限変更", edit_enquete_path(id: @enquete.id), class: "btn btn-outline-warning" %>
  <%= link_to "アンケート削除", @enquete, method: :delete, class: "btn btn-outline-danger",
    data: { confirm: "アンケート「#{@enquete.title}」を削除します。よろしいですか？" } %>
</div>